// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RF-BW7EBX_7y5ABNiTxkthddqPMu5Qs',
    appId: '1:1068640002707:web:0c5a6b8288f4db9ec7a366',
    messagingSenderId: '1068640002707',
    projectId: 'flutterboardapp-1aaff',
    authDomain: 'flutterboardapp-1aaff.firebaseapp.com',
    storageBucket: 'flutterboardapp-1aaff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Lx3xcyym3KDdvYER-UPQoHva09yiL34',
    appId: '1:1068640002707:android:3db30d33e4c29215c7a366',
    messagingSenderId: '1068640002707',
    projectId: 'flutterboardapp-1aaff',
    storageBucket: 'flutterboardapp-1aaff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA_Nv0S0dVjv39AsMga-dI_zMHwZxzOyA',
    appId: '1:1068640002707:ios:b7d96789b7d1605dc7a366',
    messagingSenderId: '1068640002707',
    projectId: 'flutterboardapp-1aaff',
    storageBucket: 'flutterboardapp-1aaff.appspot.com',
    iosClientId: '1068640002707-ben3tfarfm175f70abnjp6i70tgla6l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
